[package]
name = "strings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.34.1"
colored = "2.1.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
]

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = "0.13.0"

[[bin]]
name = "test"

[features]
default = ["strings-assertions"]
strings-assertions = [] #Disable assertions by disabling this feature
no-trace = []

